Raiders redone
loot/fallout3 pull request #431
Opened 2023-09-16 22:00 UTC by Superfly-Johnson

I know this one ain't perfect but I didn't know where to add the URL to each of the module or only the main one.

RRGoreGrafittiRemoved doesn't touch anything base Raiders Redone does so I decided to not give it any particular sorting order priority. If I find conflicts in the future I will note them.

2023-09-16 22:03 UTC, pStyl3 commented
Please rebase, as once again there's one commit from Ortham in this PR, that don't need to be there.

2023-09-16 22:30 UTC, pStyl3 commented
Though technically not necessary, we usually use the following order for the different properties we assign to plugins:
```yaml
name
url
group
after
req
inc
msg
tag
dirty
clean
```
In your case here, where we have 3 plugins that come from the same modpage, so
```yaml
RRFemalesRemoved.esp
RRGoreGrafittiRemoved.esp
RaidersRedoneModular01.esp
```
we can use a [regular expression](https://loot.github.io/docs/contributing/Regular-Expression-Regex.html) in order to assign the url to all three plugins at once.
```yaml
  - name: '(RR(Females|GoreGrafitti)Removed|RaidersRedoneModular01)\.esp'
    url:
      - link: 'https://www.nexusmods.com/fallout3/mods/2466/'
        name: 'Raiders Redone'
```
This regex can be placed at the top of your masterlist addition and after that can come the different & explicit plugin names with the information you want to assign to each of them.

2023-09-17 13:55 UTC, MacSplody commented on masterlist.yaml
> +  - name: '(RR(Females|GoreGrafitti)Removed|RaidersRedoneModular01)\.esp'
Removed the header comment as it isn't that useful for this mod.

I would place the main filename first in a regex when possible.
It's easier to find when scrolling through code,
```suggestion
  - name: '(RaidersRedoneModular01|RR(Females|GoreGrafitti)Removed)\.esp'
```

2023-09-17 14:08 UTC, MacSplody commented on masterlist.yaml
> +      - Delev
You can use brackets when a list only contains a single item.
```suggestion
    tag: [ Delev ]
```

2023-09-17 14:14 UTC, MacSplody commented
A wild edits message might be appropriate for these deleted static records.
![image](https://github.com/loot/fallout3/assets/1944639/a6978fe0-1f25-4728-9784-21891d2502f8)

2023-09-17 15:15 UTC, MacSplody commented on masterlist.yaml
> +      - Names
Factions tag can be removed, no changes made to those type of sub records.
![image](https://github.com/loot/fallout3/assets/1944639/b38a4673-ed53-4228-8076-3c37235046f6)

`Invent` can be replaced with `Invent.Add` and `Invent.Remove`.
I know Invent can be used instead of both, but using the newer separate tags makes it clear what the mod is doing.

`Names` doesn't seem that important for this file, but it shouldn't cause any major issues leaving it.

```suggestion
    tag:
      - Actors.ACBS
      - Delev
      - Invent.Add
      - Invent.Remove
      - Names
```

2023-09-17 15:18 UTC, MacSplody requested changes
A few minor changes required, the wild edits message suggestion is optional.

2023-09-17 16:32 UTC, Superfly-Johnson commented on masterlist.yaml
> +      - Names
Those deleted statics aren't a wild edit but entirely intentional, that particular plugin is meant to remove raider decals. I dunno why anyone would use it but it's why those changes have been made. I'll fixup the tags

2023-09-17 16:35 UTC, Superfly-Johnson commented on masterlist.yaml
> +      - Names
Perhaps a dangerous change edit message would be more appropriate for RRGoreGrafittiRemoved.esp?

2023-09-17 18:20 UTC, MacSplody commented on masterlist.yaml
> +      - Names
> Those deleted statics aren't a wild edit but entirely intentional, that particular plugin is meant to remove raider decals. I dunno why anyone would use it but it's why those changes have been made. I'll fixup the tags

Yeah they do fall outside wild edit due to their intent.
But they could be classed as misdirected, which does fall under the definition of a wild edit.
It's fine to delete those base objects to save time when deleting refs, but the base records should really be removed afterwards.

> Perhaps a dangerous change edit message would be more appropriate for RRGoreGrafittiRemoved.esp?

Well if we were going to add a separate message for these types of edits.
I think it should explain the potential problem with deleted base records via a linked explanation.
I'm not sure if xEdit docs cover those, maybe wryebash docs do.

2023-09-17 18:25 UTC, Superfly-Johnson commented on masterlist.yaml
> +      - Names
So should I add a wild edit message to save time?

2023-09-17 18:31 UTC, MacSplody commented on masterlist.yaml
> +      - Names
Yes you can add it, we can always revisit it if we add a separate message for deleted base records.

2023-09-18 13:48 UTC, MacSplody commented on masterlist.yaml
> +        condition: 'checksum("RRGoreGrafittiRemoved.esp", 8056F364)'
Cleaning data last for consistency.

```suggestion
  - name: 'RRGoreGrafittiRemoved.esp'
    msg:
      - <<: *wildEdits
        subs: [ 'Remove all Static records from **RRGoreGrafittiRemoved.esp**.' ]
        condition: 'checksum("RRGoreGrafittiRemoved.esp", 8056F364)'
    dirty:
      - <<: *quickClean
        crc: 0x8056F364
        util: '[FO3Edit v4.0.4](https://www.nexusmods.com/fallout3/mods/637)'
        udr: 1626
```

2023-09-18 23:34 UTC, MacSplody commented on masterlist.yaml
> +  # Raiders Redone and Modules #
```suggestion
```

2023-09-18 23:34 UTC, MacSplody approved these changes

2023-09-18 23:39 UTC, merged

2023-09-18 23:39 UTC, MacSplody commented
Thanks.